2022-08-08 18:15:59,811 INFO     ---------------------------------------------------------------------------------------------
2022-08-08 18:15:59,811 INFO     Geo: cqd
2022-08-08 18:15:59,811 INFO     Data Path: data/FB15k-237-betae
2022-08-08 18:15:59,811 INFO     #entity: 14505
2022-08-08 18:15:59,811 INFO     #relation: 474
2022-08-08 18:15:59,811 INFO     #max steps: 150000
2022-08-08 18:15:59,811 INFO     Evaluate unoins using: DNF
2022-08-08 18:15:59,811 INFO     loading data
2022-08-08 18:16:36,420 INFO     Training info:
2022-08-08 18:16:36,424 INFO     3p: 149689
2022-08-08 18:16:39,902 INFO     Validation info:
2022-08-08 18:16:39,902 INFO     3p: 5000
2022-08-08 18:16:39,904 INFO     Test info:
2022-08-08 18:16:39,904 INFO     3p: 5000
2022-08-08 18:16:42,477 INFO     Model Parameter Configuration:
2022-08-08 18:16:42,477 INFO     Parameter embeddings.0.weight: torch.Size([14505, 2000]), require_grad = True
2022-08-08 18:16:42,477 INFO     Parameter embeddings.1.weight: torch.Size([474, 2000]), require_grad = True
2022-08-08 18:16:42,477 INFO     Parameter score_transform_fun.weight: torch.Size([2, 2000]), require_grad = True
2022-08-08 18:16:42,477 INFO     Parameter score_transform_fun.bias: torch.Size([2]), require_grad = True
2022-08-08 18:16:42,477 INFO     Parameter Number: 29962002
2022-08-08 18:16:42,497 INFO     Loading checkpoint models/fb15k-237-betae...
2022-08-08 18:16:42,638 INFO     tasks = 3p
2022-08-08 18:16:42,638 INFO     init_step = 99999
2022-08-08 18:16:42,639 INFO     Start Training...
2022-08-08 18:16:42,639 INFO     learning_rate = 0
2022-08-08 18:16:42,639 INFO     batch_size = 1024
2022-08-08 18:16:42,639 INFO     hidden_dim = 1000
2022-08-08 18:16:42,639 INFO     gamma = 12.000000
posix.uname_result(sysname='Linux', nodename='bobo.local', release='3.10.0-1160.49.1.el7.x86_64', version='#1 SMP Tue Nov 30 15:51:32 UTC 2021', machine='x86_64')
Traceback (most recent call last):
  File "main.py", line 632, in <module>
    main(parse_args())
  File "main.py", line 537, in main
    log = KGReasoning.train_step(model, optimizer, train_path_iterator, args, step)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/models.py", line 674, in train_step
    model.forward(positive_sample=positive_sample,
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 445, in forward
    scores = d2.query_3p(entity_embeddings=self.embeddings[0],
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/discrete.py", line 161, in query_3p
    atom1_scores_3d = atom1_scores_3d.repeat(1, atom3_scores_3d.shape[1] // atom1_scores_3d.shape[1], 1)
RuntimeError: CUDA out of memory. Tried to allocate 3.54 GiB (GPU 0; 15.90 GiB total capacity; 13.75 GiB already allocated; 1.31 GiB free; 13.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
